# Generated by Django 4.2.25 on 2025-10-26 02:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="e.g. pieces, kg, sets, rolls...",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("instructor", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("capacity", models.PositiveIntegerField(default=20)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "materials",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Materials required for this workshop",
                        related_name="workshops",
                        to="workshops.material",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workshops",
                        to="events.place",
                    ),
                ),
            ],
        ),
    ]
